### ISSUE TITLE
图片获取图片时显示加载异常，在网页中无法正常显示，但是使用获取的链接可以直接打开图片

### ISSUE THREAD

**Issue by ULeeBu** [liuyiwuqing/halo-plugin-picture-bed#1]
![image](https://github.com/liuyiwuqing/halo-plugin-picture-bed/assets/40551517/3e108a20-91f4-4720-895a-da337c1ca161)

**Comment by liuyiwuqing** [comment]
检查下图床服务是否开启了防盗链功能

**Comment by liuyiwuqing** [comment]
> ![image](https://private-user-images.githubusercontent.com/40551517/334251296-3e108a20-91f4-4720-895a-da337c1ca161.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjUyNjYsIm5iZiI6MTcxNjg2NDk2NiwicGF0aCI6Ii80MDU1MTUxNy8zMzQyNTEyOTYtM2UxMDhhMjAtOTFmNC00NzIwLTg5NWEtZGEzMzdjMWNhMTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAyNTYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNzI0M2NkMzI0OTk4ZjVlMDA0OTI0NzEwMGFiMDY4NzA4NGQ0ODJiMjZlMDBhN2JlOTA3YjI5NGVlMmRmMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G-G1yqw8TspolTnIjxk_1BqjkNBiQgdOGs_0qJ8IQ8I)

@ULeeBu 
1. 检查图床站点和博客站点是否都是https协议，如果博客站点是https，图床也必须是https
2. 检查图床服务是否开启了防盗链

**Comment by ULeeBu** [comment]
切换到https已经正常 感谢

**Comment by liuyiwuqing** [comment]
> 切换到https已经正常 感谢

good
