### ISSUE TITLE
兰空图床只支持上传图片

### ISSUE THREAD

**Issue by wsj20010128** [liuyiwuqing/halo-plugin-picture-bed#2]
Halo版本2.16.2
图片是jpg格式，链接: https://img.wit.ee/wallhaven-zyxvqy.jpg
连接兰空图床正常，图片在halo后台可以正常显示，但是上传到图库时显示仅支持上传图片

**Comment by liuyiwuqing** [comment]
> Halo版本2.16.2 图片是jpg格式，链接: https://img.wit.ee/wallhaven-zyxvqy.jpg 连接兰空图床正常，图片在halo后台可以正常显示，但是上传到图库时显示仅支持上传图片
针对于标题所述，仅支持上传图片文件，其他文件不支持

已测试所提供的图片，上传和显示均正常
<img width="1709" alt="image" src="https://github.com/liuyiwuqing/halo-plugin-picture-bed/assets/52553268/49192068-abb1-4198-b2f0-fdea7c6f941a">
<img width="1709" alt="image" src="https://github.com/liuyiwuqing/halo-plugin-picture-bed/assets/52553268/7bcb45f1-7e5b-4928-bf99-c3e64dbcbb16">

**Comment by wsj20010128** [comment]
在图库里选从附件库中的兰空图床再上传时会显示只支持选择图片
视频链接：https://drive.witnessj.com/s/WJhg

**Comment by liuyiwuqing** [comment]
> 在图库里选从附件库中的兰空图床再上传时会显示只支持选择图片 视频链接：https://drive.witnessj.com/s/WJhg

在1.1.0版本修复了
https://github.com/liuyiwuqing/halo-plugin-picture-bed/releases/tag/v1.1.0
