### ISSUE TITLE
突然出现服务器错误

### ISSUE THREAD

**Issue by exixia** [liuyiwuqing/halo-plugin-picture-bed#4]
![image](https://github.com/user-attachments/assets/a06d2371-bda3-446f-8e13-d3c60f899fb6)
不知道为什么出现这个了，点击Halo里工具管理里的图床管理出现的，刚安装好是正常的

**Comment by mogumc** [comment]
不要复制例子里面的api地址  https://sm.ms/api/v2/

**Comment by liuyiwuqing** [comment]
> ![image](https://private-user-images.githubusercontent.com/37772580/365850707-a06d2371-bda3-446f-8e13-d3c60f899fb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjkzMzEsIm5iZiI6MTcyODUyOTAzMSwicGF0aCI6Ii8zNzc3MjU4MC8zNjU4NTA3MDctYTA2ZDIzNzEtYmRhMy00NDZmLThlMTMtZDNjNjBmODk5ZmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAyNTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NWJlNGZhM2IxOGFkZTIxMWIzMDA0MGEyZTY2MGQ4Nzg0NzJlNWMwMTk0M2Y0MDBkMWIxNmQzNWViOTY0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ICEP-Ro0M65NtjqPussgG7vL82RTuFXip15ChzGQGPk) 不知道为什么出现这个了，点击Halo里工具管理里的图床管理出现的，刚安装好是正常的

如楼下所说，应该是例子中的接口失效了，可以换个其他的接口

**Comment by exixia** [comment]
> > ![image](https://private-user-images.githubusercontent.com/37772580/365850707-a06d2371-bda3-446f-8e13-d3c60f899fb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjkzMzEsIm5iZiI6MTcyODUyOTAzMSwicGF0aCI6Ii8zNzc3MjU4MC8zNjU4NTA3MDctYTA2ZDIzNzEtYmRhMy00NDZmLThlMTMtZDNjNjBmODk5ZmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAyNTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NWJlNGZhM2IxOGFkZTIxMWIzMDA0MGEyZTY2MGQ4Nzg0NzJlNWMwMTk0M2Y0MDBkMWIxNmQzNWViOTY0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ICEP-Ro0M65NtjqPussgG7vL82RTuFXip15ChzGQGPk) 不知道为什么出现这个了，点击Halo里工具管理里的图床管理出现的，刚安装好是正常的
> 
> 如楼下所说，应该是例子中的接口失效了，可以换个其他的接口

不好意思，我没有找到其他的接口

**Comment by liuyiwuqing** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/37772580/365850707-a06d2371-bda3-446f-8e13-d3c60f899fb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjkzMzEsIm5iZiI6MTcyODUyOTAzMSwicGF0aCI6Ii8zNzc3MjU4MC8zNjU4NTA3MDctYTA2ZDIzNzEtYmRhMy00NDZmLThlMTMtZDNjNjBmODk5ZmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAyNTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NWJlNGZhM2IxOGFkZTIxMWIzMDA0MGEyZTY2MGQ4Nzg0NzJlNWMwMTk0M2Y0MDBkMWIxNmQzNWViOTY0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ICEP-Ro0M65NtjqPussgG7vL82RTuFXip15ChzGQGPk) 不知道为什么出现这个了，点击Halo里工具管理里的图床管理出现的，刚安装好是正常的
> > 
> > 
> > 如楼下所说，应该是例子中的接口失效了，可以换个其他的接口
> 
> 不好意思，我没有找到其他的接口

可以试下 张安心图床 https://pic.xiaozhangstu.com/
