### ISSUE TITLE
兰空图床支持多api

### ISSUE THREAD

**Issue by mogumc** [liuyiwuqing/halo-plugin-picture-bed#5]
网上也有很多免费图床采用兰空 希望能够支持添加多个兰空图床并支持自行命名
🐲👍

**Comment by liuyiwuqing** [comment]
我研究研究

**Comment by liuyiwuqing** [comment]
> 网上也有很多免费图床采用兰空 希望能够支持添加多个兰空图床并支持自行命名 🐲👍

我研究研究

**Comment by liuyiwuqing** [comment]
> 网上也有很多免费图床采用兰空 希望能够支持添加多个兰空图床并支持自行命名 🐲👍

[v1.2.1](https://github.com/liuyiwuqing/halo-plugin-picture-bed/releases/tag/v1.2.1)
已支持！
