### ISSUE TITLE
重新卸载，安装最新版后，页面无法加载，日志报错如下

### ISSUE THREAD

**Issue by Vita0519** [liuyiwuqing/halo-plugin-picture-bed#8]
[2Kmyhalo2193  | 	Suppressed: java.lang.Exception: #block terminated with an error
[2Kmyhalo2193  | 		at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:129) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
[2Kmyhalo2193  | 		at reactor.core.publisher.Mono.blockOptional(Mono.java:1831) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1]
[2Kmyhalo2193  | 		at run.halo.doc.infra.search.DocLuceneIndexReconciler.lambda$reconcile$0(DocLuceneIndexReconciler.java:45) ~[na:na]
[2Kmyhalo2193  | 		at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na]
[2Kmyhalo2193  | 		at run.halo.doc.infra.search.DocLuceneIndexReconciler.reconcile(DocLuceneIndexReconciler.java:31) ~[na:na]
[2Kmyhalo2193  | 		at run.halo.doc.infra.search.DocLuceneIndexReconciler.reconcile(DocLuceneIndexReconciler.java:20) ~[na:na]
[2Kmyhalo2193  | 		at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.20.8.jar:na]
[2Kmyhalo2193  | 		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
[2Kmyhalo2193  | 		at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
[2Kmyhalo2193  | 		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
[2Kmyhalo2193  | 		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
[2Kmyhalo2193  | 		... 1 common frames omitted

**Comment by liuyiwuqing** [comment]
> �[2Kmyhalo2193 | Suppressed: java.lang.Exception: #block terminated with an error �[2Kmyhalo2193 | at reactor.core.publisher.BlockingOptionalMonoSubscriber.blockingGet(BlockingOptionalMonoSubscriber.java:129) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1] �[2Kmyhalo2193 | at reactor.core.publisher.Mono.blockOptional(Mono.java:1831) ~[reactor-core-3.7.0-RC1.jar:3.7.0-RC1] �[2Kmyhalo2193 | at run.halo.doc.infra.search.DocLuceneIndexReconciler.lambda$reconcile$0(DocLuceneIndexReconciler.java:45) ~[na:na] �[2Kmyhalo2193 | at java.base/java.util.Optional.ifPresent(Unknown Source) ~[na:na] �[2Kmyhalo2193 | at run.halo.doc.infra.search.DocLuceneIndexReconciler.reconcile(DocLuceneIndexReconciler.java:31) ~[na:na] �[2Kmyhalo2193 | at run.halo.doc.infra.search.DocLuceneIndexReconciler.reconcile(DocLuceneIndexReconciler.java:20) ~[na:na] �[2Kmyhalo2193 | at run.halo.app.extension.controller.DefaultController$Worker.run(DefaultController.java:163) ~[api-2.20.8.jar:na] �[2Kmyhalo2193 | at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na] �[2Kmyhalo2193 | at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na] �[2Kmyhalo2193 | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na] �[2Kmyhalo2193 | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na] �[2Kmyhalo2193 | ... 1 common frames omitted

从提供的日志分析，并没有看到图床的相关报错日志
页面无法加载可从如下几点进行排查：

1. 检查是否插件不兼容，目前已知不兼容插件：Markdown / HTML 内容块、链接安全跳转中台
2. 检查图床接口是否正常
