### ISSUE TITLE
希望添加 PicGo图床

### ISSUE THREAD

**Issue by KingPrimes** [liuyiwuqing/halo-plugin-picture-bed#9]
希望添加这个图床https://www.picgo.net/

**Comment by liuyiwuqing** [comment]
已查看接口文档https://v4-docs.chevereto.com/developer/api/api-v1.html
该图床暂时不支持对接，接入图床需满足以下要求：

1. 提供获取图片列表的接口（必要）
2. 提供图片上传的接口（必要）
3. 提供图片删除的接口（非必要）
